services:
  postgres:
    image: postgres:16-alpine
    container_name: roadmap_postgres
    restart: unless-stopped
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - pg_stat_statements.track=all
    environment:
      POSTGRES_DB: roadmap_db
      POSTGRES_USER: roadmap_user
      POSTGRES_PASSWORD: roadmap_pass
    ports:
      - "5433:5432"
    volumes:
      - roadmap_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roadmap_user -d roadmap_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: roadmap_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@roadmap.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  roadmap_pg_data:
