package com.example.roadmap.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(description = "Detailed async task status with optional result")
public class AsyncTaskStatusDto {

  @Schema(description = "Async task identifier",
      example = "91e0c13b-81d3-43a0-b687-dc25c6cb9497")
  private final String taskId;

  @Schema(description = "Roadmap id being processed", example = "2")
  private final Long roadMapId;

  @Schema(description = "Current task status", example = "RUNNING")
  private final AsyncTaskStatus status;

  @Schema(description = "When the task was created", example = "2026-04-07T12:00:00+03:00")
  private final OffsetDateTime createdAt;

  @Schema(description = "When the task actually started on async executor", example = "2026-04-07T12:00:01+03:00")
  private final OffsetDateTime startedAt;

  @Schema(description = "When the task finished", example = "2026-04-07T12:00:02+03:00")
  private final OffsetDateTime completedAt;

  @Schema(description = "Failure message if the task ended with error", example = "RoadMap with id=999 not found")
  private final String errorMessage;

  @Schema(description = "Analytics report generated by task when status is COMPLETED")
  private final RoadMapAnalyticsReportDto report;
}
