spring.application.name=roadmap

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/roadmap_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:roadmap_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:roadmap_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
